# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under kw_mlops/resources/*
# and kw_mlops/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for kw_mlops Prod

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./kw_mlops

env:
  DATABRICKS_TOKEN: ${{ secrets.PROD_WORKSPACE_TOKEN }}

jobs:
  prod:
    concurrency: kw_mlops-prod-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.212.2
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t prod
